name: Scheduled Make All

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 2 10,15,20 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
    - name: Run make all
      run: make all


    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update generated files"
        git push origin master
      env:
          GITHUB_TOKEN: ${{ secrets.HAYDEN_TOKEN }}